import * as React from "react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { LocalizationProvider, AdapterDayjs } from "@/utils/utils";
import TemplateFrameWrapper from "@/theme/TemplateFrameWrapper";

export const metadata = {
  title: 'Finance personal',
  description: 'Generated by Next.js',
}

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <LocalizationProvider dateAdapter={AdapterDayjs}>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <TemplateFrameWrapper>
              {props.children}
            </TemplateFrameWrapper>
          </AppRouterCacheProvider>
        </LocalizationProvider>
      </body>
    </html>
  );
}