import * as React from "react";
import TemplateFrameWrapper from "@/theme/TemplateFrameWrapper";
import NextAuthWrapper from "@/utils/next.auth.wrapper";
import SnackbarProvider from "@/utils/snackbar.wrapper";

export const metadata = {
  title: "Finance personal",
  description: "Generated by Next.js",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <SnackbarProvider>
      <NextAuthWrapper>
        <TemplateFrameWrapper>{props.children}</TemplateFrameWrapper>
      </NextAuthWrapper>
    </SnackbarProvider>
  );
}
